.TH NSUDS "1" "December 16th, 2009" "nsuds 0.5B" "Nsuds - The Ncurses Sudoku System"

.SH NAME
Nsuds - The Ncurses Sudoku System
.SH SYNOPSIS
.B ncurses [\fI-hvcC\fR]
.SH DESCRIPTION
Nsuds is a text-graphical sudoku game with pencil-marking support.
.P
Mandatory arguments to long options are mandatory for short options too.
.TP 5
-c --color[=WHEN]
Control when to use colors. WHEN may be `never', `auto' or `always'. Defaults
to `auto'.
.TP
-C --no-color
Synonym for --color=never.
.TP
-h --help
Display a help message and exit.
.TP
-v --version
Output version and author information and exit.
.P
Note: Long options may be passed with a single dash.

.SH HELP
Press '?' to get detailed in-game help.

.SH AUTHOR
Written by  Vincent Launchbury <vincent@doublecreations.com> 2009

.SH REPORTING BUGS
Report nsuds bugs to <vincent@doublecreations.com>
.br
Nsuds homepage: <http://www.sourceforge.net/projects/nsuds/>
.br
Bugs may also be reported using the sourceforge tracker system.

.SH COPYRIGHT
Copyright (C) Vincent Launchbury 2009. 
.P
License: GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl.html>. This is free software: you are free to change and redistribute it. There is NO WARRANTY, to the extent permitted by law.


.SH SEE ALSO
Project summary:  <http://www.sf.net/projects/nsuds/>.
